# Generated by Django 4.0.4 on 2022-05-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255555, verbose_name='name')),
                ('image', models.ImageField(blank=True, upload_to='image/%Y/%m/%d', verbose_name='Фотки')),
                ('text', models.CharField(blank=True, db_index=True, max_length=255555, verbose_name='text')),
            ],
        ),
    ]
